language: python

sudo: required

notifications:
  email: never

python:
  - "2.7"

addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.14/
  - export PATH=$PATH:/home/travis/virtualenv/python2.7.14/

install:
  - pip install -r dev-requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - py.test -v

after_success:
  - coveralls
